//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaSi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietAlbum
    {
        public string MaCaSi { get; set; }
        public string MaBaiHat { get; set; }
        public string MaAlbum { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual BaiHat BaiHat { get; set; }
        public virtual CaSi CaSi { get; set; }
    }
}
