//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaSi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyCaSyEntities : DbContext
    {
        public QuanLyCaSyEntities()
            : base("name=QuanLyCaSyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<BaiHat> BaiHat { get; set; }
        public virtual DbSet<CaSi> CaSi { get; set; }
        public virtual DbSet<ChiTietAlbum> ChiTietAlbum { get; set; }
        public virtual DbSet<NhacSi> NhacSi { get; set; }
        public virtual DbSet<NhaSanXuat> NhaSanXuat { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
